openapi: 3.0.3
info:
  version: 1.0.0
  title: Provision API
  description: Provision api 
  x-sla:
    $ref: ./plans.yaml
security:
  - BearerAuth: []
paths:
  /api/v1/provisions:
    x-router-controller: provisionsController
    get:
      description: Returns all provisions
      operationId: getprovisions
      responses:
        200:
          description: provisions list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/provisions'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /api/v1/provisions/{id}:
    x-router-controller: provisionsController
    get:
      description: Returns a single provision by its id
      operationId: findByid
      parameters:
        - required: true
          name: id
          description: id of the provision to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: provision found by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/provisions'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    provision:
        type: object
        required:
          - id
        properties:
          disposal_number:
            type: number
          province:
            type: string

    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true